### ISSUE TITLE
[优化] my-account界面

### ISSUE THREAD

**Issue by MakesYT** [work7z/MDGJX#3]
![04d90b7062267cf028c041bbe2bb1a8f](https://github.com/work7z/MDGJX/assets/42534870/05eeb713-3291-4647-8dc0-4b27980ca671)
1. my-account界面图标对齐和大小错误
2. 加入时间建议格式化(2022年9月15日星期四 18:04:50)

**Comment by work7z** [comment]
好的，我们正在处理这一处逻辑，谢谢反馈

**Comment by work7z** [comment]
此问题已修复，并且也修复了首次登录提示登录无效的bug
