### ISSUE TITLE
[优化] i18n界面

### ISSUE THREAD

**Issue by MakesYT** [work7z/MDGJX#4]
![image](https://github.com/work7z/MDGJX/assets/42534870/6eedf330-bac2-4e23-aaf6-9db1f9d10eb0)
1. 暗色模式下按钮边框样式与其他边框不同

**Comment by work7z** [comment]
感谢反馈

这个应该是原本UI库的风格是这么设计的，我们检查如何改进这一块

**Comment by work7z** [comment]
目前UI这一块暂时跟随原UI框架，暂时不修改了哈，等后面计划了我们再开
