### ISSUE TITLE
v5.4.96版本本地部署只有6个功能项

### ISSUE THREAD

**Issue by VictorWells** [work7z/MDGJX#87]
我看介绍不是都有几十个功能项吗？为啥我部署只有6个？
<img width="1439" alt="image" src="https://github.com/work7z/MDGJX/assets/34592730/1d2ed4bc-8546-440a-a0e2-18497491eee0">

**Comment by work7z** [comment]
您好，默认情况下我们不会安装所有插件，请您跳转到插件商店，点击安装后就会有全部功能了哈
