### ISSUE TITLE
关于Readme中编译安装可能存在的问题

### ISSUE THREAD

**Issue by sunyong01** [work7z/MDGJX#96]
我确保已经配置了环境变量并source了
<img width="392" alt="image" src="https://github.com/user-attachments/assets/cd3728b5-a353-47b7-bf70-cc194e78a0bf">
在项目根目录下执行这一步时，报错
cd $MDGJX_ROOT/modules/web2 && npm install -S -D --force
<img width="611" alt="image" src="https://github.com/user-attachments/assets/53a1ea5e-c14c-4e06-9b0c-99a9f1572a3e">

**Comment by sunyong01** [comment]
#95 这个问题已经得到解决

**Comment by work7z** [comment]
好的， 谢谢排查此问题
